apiVersion: v1
kind: Service
metadata:
  name: {{ include "rota.fullname" . }}-proxy
  labels:
    {{- include "rota.labels" . | nindent 4 }}
    app.kubernetes.io/component: core
  {{- with .Values.core.proxyService.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.core.proxyService.type }}
  {{- if and (has .Values.core.proxyService.type (list "LoadBalancer" "NodePort")) .Values.core.proxyService.externalTrafficPolicy }}
  externalTrafficPolicy: {{ .Values.core.proxyService.externalTrafficPolicy }}
  {{- end }}
  {{- with .Values.core.proxyService.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
    {{- include "rota.coreSelectorLabels" . | nindent 4 }}
  ports:
    - name: proxy
      port: {{ .Values.core.proxyPort }}
      targetPort: proxy
      protocol: TCP
    {{- if .Values.core.socksPort }}
    - name: socks
      port: {{ .Values.core.socksPort }}
      targetPort: socks
      protocol: TCP
    {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "rota.fullname" . }}-api
  labels:
    {{- include "rota.labels" . | nindent 4 }}
    app.kubernetes.io/component: core
  {{- with .Values.core.apiService.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.core.apiService.type }}
  selector:
    {{- include "rota.coreSelectorLabels" . | nindent 4 }}
  ports:
    - name: api
      port: {{ .Values.core.apiPort }}
      targetPort: api
      protocol: TCP
