{{- $data := include "rota.secretData" . | trim }}
{{- if $data }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rota.secretName" . }}
  labels:
    {{- include "rota.labels" . | nindent 4 }}
type: Opaque
data:
  {{- $data | nindent 2 }}
{{- end }}
