{{- if .Values.metrics.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "rota.fullname" . }}-core
  labels:
    {{- include "rota.labels" . | nindent 4 }}
    {{- with .Values.metrics.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "rota.coreSelectorLabels" . | nindent 6 }}
  endpoints:
    - port: api
      path: /metrics
      interval: {{ .Values.metrics.serviceMonitor.interval }}
      {{- with .Values.metrics.serviceMonitor.tokenSecret }}
      authorization:
        type: Bearer
        credentials:
          name: {{ .name }}
          key: {{ .key }}
      {{- else }}
      {{- if and $.Values.secrets.metricsToken (not $.Values.secrets.existingSecret) }}
      authorization:
        type: Bearer
        credentials:
          name: {{ include "rota.secretName" $ }}
          key: METRICS_TOKEN
      {{- end }}
      {{- end }}
{{- end }}
