{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "rota.serviceAccountName" . }}
  labels:
    {{- include "rota.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
# Rota doesn't call the Kubernetes API.
automountServiceAccountToken: false
{{- end }}
